---
- src: yatesr.timezone

# from GitHub
- src: https://bitbucket.org/dat/ansible-etcd.git
  name: etcd
  scm: git

- src: https://bitbucket.org/dat/ansible-docker.git
  name: docker
  scm: git

- src: https://bitbucket.org/dat/ansible-flannel.git
  name: flannel
  scm: git

- src: https://bitbucket.org/dat/ansible-k8s-master.git
  name: k8s-master
  scm: git

- src: https://bitbucket.org/dat/ansible-k8s-worker.git
  name: k8s-worker
  scm: git

- src: https://bitbucket.org/dat/ansible-locksmith.git
  name: locksmith
  scm: git

- src: https://bitbucket.org/dat/ansible-timesyncd.git
  name: timesyncd
  scm: git

- src: https://bitbucket.org/dat/ansible-udev.git
  name: udev
  scm: git

- src: https://bitbucket.org/dat/ansible-sysctl.git
  name: sysctl
  scm: git

- src: https://bitbucket.org/dat/ansible-transparent-hugepages.git
  name: transparent_hugepages
  scm: git
